name: google_ads_api_report
keys:
  -
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.4.4'
  database: mysql:5.7
  cache: none
  xdebug: true
  webroot: public
  via: nginx
proxy:
  mail:
    - mail.lndo.site
services:
  appserver:
    build_as_root:
      - apt-get update -y && apt-get install -y vim && apt-get install -y jq
    run:
      - cd /var/www && touch .bashrc
      - curl https://get.volta.sh | bash
      - COMPOSER_PROCESS_TIMEOUT=3600 composer install -vvv
  database:
    type: mysql
    portforward: 3309
    run_as_root:
      - mysql -uroot -e 'DROP DATABASE IF EXISTS laravel;'
      - mysql -uroot -e 'DROP DATABASE IF EXISTS google_ads_local;'
      - mysql -uroot -e 'DROP DATABASE IF EXISTS google_ads_test;'
      - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS google_ads_local CHARACTER SET utf8 COLLATE utf8_general_ci;'
      - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS google_ads_test CHARACTER SET utf8 COLLATE utf8_general_ci;'
  # http://mail.lndo.site:49191/ or http://localhost:49191/
  mail:
    type: mailhog
    hogfrom:
      - appserver


